//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.taichang.dao;

import android.content.Context;
import com.taichang.bean.AccountPref_;

public final class AccountDao_
    extends AccountDao
{

    private Context context_;

    private AccountDao_(Context context) {
        context_ = context;
        init_();
    }

    public static AccountDao_ getInstance_(Context context) {
        return new AccountDao_(context);
    }

    private void init_() {
        pref = new AccountPref_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
