//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.taichang.dao;

import android.content.Context;
import com.taichang.bean.SettingsPref_;

public final class SettingsDao_
    extends SettingsDao
{

    private Context context_;

    private SettingsDao_(Context context) {
        context_ = context;
        init_();
    }

    public static SettingsDao_ getInstance_(Context context) {
        return new SettingsDao_(context);
    }

    private void init_() {
        pref = new SettingsPref_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
