//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.taichang.gps;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyLocationProvider_
    extends MyLocationProvider
{

    private Context context_;
    private static MyLocationProvider_ instance_;

    private MyLocationProvider_(Context context) {
        context_ = context;
    }

    public static MyLocationProvider_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new MyLocationProvider_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        mLocationListener = MyLocationListener_.getInstance_(context_);
        mContext = context_;
        init();
    }

}
