//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.taichang.gps;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyLocationListener_
    extends MyLocationListener
{

    private Context context_;
    private static MyLocationListener_ instance_;

    private MyLocationListener_(Context context) {
        context_ = context;
    }

    public static MyLocationListener_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new MyLocationListener_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
