//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.taichang.bean;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class AccountPref_
    extends SharedPreferencesHelper
{


    public AccountPref_(Context context) {
        super(context.getSharedPreferences("AccountPref", 0));
    }

    public AccountPref_.AccountPrefEditor_ edit() {
        return new AccountPref_.AccountPrefEditor_(getSharedPreferences());
    }

    public StringPrefField userid() {
        return stringField("userid", "");
    }

    public final static class AccountPrefEditor_
        extends EditorHelper<AccountPref_.AccountPrefEditor_>
    {


        AccountPrefEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<AccountPref_.AccountPrefEditor_> userid() {
            return stringField("userid");
        }

    }

}
