//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.taichang;

import com.taichang.gps.MyLocationProvider_;

public final class AppApplication_
    extends AppApplication
{

    private static AppApplication INSTANCE_;

    public static AppApplication getInstance() {
        return INSTANCE_;
    }

    /**
     * Visible for testing purposes
     * 
     */
    public static void setForTesting(AppApplication application) {
        INSTANCE_ = application;
    }

    @Override
    public void onCreate() {
        INSTANCE_ = this;
        init_();
        super.onCreate();
    }

    private void init_() {
        mMyLocationProvider = MyLocationProvider_.getInstance_(this);
    }

}
